server:
  port: 8099
  servlet:
    context-path: /edu
spring:
  datasource:
    url: jdbc:mysql://121.36.228.230:3306/edu-live?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: xyz8.live.config.MybatisPlusOutImpl